### PR TITLE
convert to oxmysql v1.9.0

### PR DESCRIPTION
**Pull request by zfbx**
Haven't tested personally, was requested and figured I'd submit a PR to help out

### CODE REVIEW

**Comment by WolfieValeo** [comment]
Can confirm his updates do work!

**Review by ARSSANTO — APPROVED** [review]
Working smoothlyyyy

**Comment by zfbx** [comment]
Wait.. I'm confused.. is everything fine or not? xD spawning as Michael sounds like not fine... is that fault of my edits or something else? @ARSSANTO

**Comment by ARSSANTO** [comment]
every thing perfect after fetch all

**Pull request merged**
